@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}
@refreshToken = {{authenticate.response.body.refreshToken}}

# RECADOS
#todos
#com query parameters
GET {{baseUrl}}/recados/
?limit=4
&offset=1
Authorization: Bearer {{authToken}}
###
GET {{baseUrl}}/recados
Authorization: Bearer {{authToken}}

### FIND ONE
GET {{baseUrl}}/recados/1
Authorization: Bearer {{authToken}}

### POST 
POST {{baseUrl}}/recados/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "Texto de alr para d",
    "paraId": 2
    //"blabla": "não vai add por causa do atributo"
}

### UPDATE

PATCH {{baseUrl}}/recados/3
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "já testei"
    //"blabla": "não vai add por causa do atributo"
}

### DELETE 

DELETE {{baseUrl}}/recados/19
Authorization: Bearer {{authToken}}
### DELETE não funciona 

DELETE {{baseUrl}}/recados/abc


# USUARIOS
#todos
###
GET {{baseUrl}}/usuario
Authorization: Bearer {{authToken}}
### FIND ONE
GET {{baseUrl}}/usuario/1
Authorization: Bearer {{authToken}}
### POST 
POST {{baseUrl}}/usuario/
Content-Type: application/json

{
    "name": "rocha",
    "email": "rocha@gmail.com",
    "password": "123456"
    //"blabla": "não vai add por causa do atributo"
}

### UPDATE

PATCH {{baseUrl}}/usuario/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "routePolicies": ["createRecado", "udpateRecado", "deleteRecado", 
    "findAllRecados", "findOneRecado", "createUsuario", "findAllUsuarios", 
    "findOneUsuario", "udpateUsuario", "deleteUsuario"]
    //"name": "daniel",
    //"password": "123456"
    //"blabla": "não vai add por causa do atributo"
}

### DELETE 

DELETE {{baseUrl}}/usuario/11
Authorization: Bearer {{authToken}}

### DELETE não funciona 
DELETE {{baseUrl}}/usuario/abc
Authorization: Bearer {{authToken}}

### AUTH
# @name authenticate
POST {{baseUrl}}/auth/
Content-Type: application/json

{
    "email": "rocha@gmail.com",
    "password": "123456"
}

### Re - autenticação
# @name reAuthenticate
POST {{baseUrl}}/auth/refresh/
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}