export const SERVER_NAME = 'SERVER_NAME';
export const ONLY_LOWERCASE_LETTER_REGEX = 'ONLY_LOWERCASE_LETTER_REGEX';
export const REMOVE_SPACES_REGEX = 'REMOVE_SPACES_REGEX';
//factory
export const ONLY_LOWERCASE_LETTER_REGEX_FACTORY =
  'ONLY_LOWERCASE_LETTER_REGEX_FACTORY';
export const REMOVE_SPACES_REGEX_FACTORY = 'REMOVE_SPACES_REGEX_FACTORY';
