@baseUrl = http://localhost:3000

# RECADOS
#todos
#com query parameters
GET {{baseUrl}}/recados/?limit=10&offset=10
###
GET {{baseUrl}}/recados

### FIND ONE
GET {{baseUrl}}/recados/2

### POST 
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "ggggg",
    "de": "Joana",
    "para": "joao"
    //"blabla": "não vai add por causa do atributo"
}

### UPDATE

PATCH {{baseUrl}}/recados/5
Content-Type: application/json

{
     "texto": "teste",
    "de": "não atualiza pq nao pode",
    "para": "joao",
    "lido": true
    //"blabla": "não vai add por causa do atributo"
}

### DELETE 

DELETE {{baseUrl}}/recados/2

### DELETE não funciona 

DELETE {{baseUrl}}/recados/abc


# USUARIOS
#todos
###
GET {{baseUrl}}/usuario

### FIND ONE
GET {{baseUrl}}/usuario/1

### POST 
POST {{baseUrl}}/usuario/
Content-Type: application/json

{
    "name": "ggggg",
    "email": "daniel@gmail.com",
    "passwordHash": "Joana"
    //"blabla": "não vai add por causa do atributo"
}

### UPDATE

PATCH {{baseUrl}}/usuario/1
Content-Type: application/json

{
    "name": "daniel",
    "password": "123456"
    //"blabla": "não vai add por causa do atributo"
}

### DELETE 

DELETE {{baseUrl}}/usuario/2

### DELETE não funciona 

DELETE {{baseUrl}}/usuario/abc